title: Simon Choppin # your name (or website title) here
logo: "/images/SimonProfile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist
  <br><br>
  Portfolio of projects of particular personal interest
  <br><br>
  <a href="https://www.linkedin.com/in/schoppin/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
